### ISSUE TITLE
Bounds-safe interface for pointer to functions

### ISSUE THREAD

**Issue by saeednj** [Microsoft/checkedc#171]
Hello,

I wanted to use the concept of bounds-safe interface but for an interface that uses function pointers for a set of callbacks. Consider the example below:
```
typedef int (*callback_fn1) (int *a, int n);
typedef void (*callback_fn2) (int *a, int *b, int n);
struct interface {
    callback_fn1 cb1;
    callback_fn2 cb2;
};
```
Let's say that there are two components that implement this interface. One is checked and the other is unchecked.

I have tried adding the bounds in the `typedef`:
```
typedef int (*callback_fn1) (int *a : count(n), int n);
```
But the implicit conversion from `array_ptr<int>` to `int*` from checked code side gives a compiler error.
Also adding `itype` declaration to the struct members gave the same error.
```
struct interface {
    callback_fn1 cb1 : itype(_Ptr<int(int * : itype(_Array_ptr<int>), int)>);
```
It seems that the bounds-safe information can not be propagated through `typedef`.

From the checked code, I can explicitly cast from `array_ptr<int>` to `int *` and pass the pointer to the callback function and cast back inside the checked callback function, but that doesn't seem like a clean solution.

How the bounds-safe interface should be used in this case?

Thanks
Saeed

**Comment by dtarditi** [comment]
Hi Saeed,

Thanks for opening this issue!   It is a great question and feedback.

Issue #81 points out that where to put bounds-safe interfaces on function pointers is confusing.   There are several possibilities and we don't offer clear enough guidance in the documentation.   I agree that it makes sense to put the bounds-safe interfaces on function parameters and return types, but we end up with the problem that the function pointer type itself remains  an unchecked pointer.  That would prevent the function pointer type from being used in checked scopes.

When it comes to function pointers, my guidance is to try to make sure that the interface type specified for a variable or member with function pointer type is completely checked.    This will allow the variable or member to be used in checked scopes.

I reworked your example to make the interface type on `cb1` be completely checked.   Here's the code along with some sample code that uses it.  It compiles fine:
```
#include <stdchecked.h>

typedef int(*callback_fn1) (int *a, int n); 

struct interface {
  callback_fn1 cb1 : itype(ptr<int (array_ptr<int> arr : count(n), int n)>);
};

#pragma BOUNDS_CHECKED ON

extern int f(array_ptr<int> arr : count(n), int n);

void test(void) {
  struct interface D;
  D.cb1 = f;
}
```
Now, you should be able to go on to refine callback_fn1 so that it can be dereferenced and applied to checked pointers:
```
typedef int(*callback_fn1) (int *a : count(n) , int n); 
void test2(callback_fn1 fn, array_ptr<int> arr : count(k), int k) {
   (*fn)(arr, k);
}
```
We get an error message, which looks like either unimplemented functionality or a compiler bug to me:
```
callback2.c:6:9: error: passing '_Array_ptr<int>' to parameter of incompatible type 'int *'
  (*fn)(arr, k);
        ^~~
1 error generated.
```
I'll open an issue to track this. Within  our modified version of clang, we've modified function types so that they hold bounds information for parameters.  So we have a place to store the information needed for the bounds-safe interface for `*fn`.     The information may be missing (not being propagated) or we might not be looking it, but conceptually our implementation supports this.   

Now, we can use a typedef'ed type when defining the itype for `cb1`.  The following code compiles fine:
```
#include <stdchecked.h>

typedef int(*callback_fn1) (int *a : count(n) , int n); 
typedef ptr<int (array_ptr<int> arr : count(n), int n)> checked_callback_fn1;

struct interface {
  callback_fn1 cb1 : itype(checked_callback_fn1);
};

#pragma BOUNDS_CHECKED ON

extern int f(array_ptr<int> arr : count(n), int n);

void test(void) {
  struct interface D;
  D.cb1 = f;
}
```

**Comment by dtarditi** [comment]
I've opened https://github.com/Microsoft/checkedc-clang/issues/323 to track the compiler issue.

**Comment by saeednj** [comment]
Hi David,

I see your point on making the function pointer checked as well.
I was seeing the same compile error when dereferencing the function pointer. Thanks for tracking the issue.

Thanks
Saeed

**Comment by dtarditi** [comment]
The compiler issues around function pointers with bounds-safe interfaces have been fixed.   Thank you @saeednj for your feedback.
