### ISSUE TITLE
Handling void* polymorphism

### ISSUE THREAD

**Issue by mwhicks1** [Microsoft/checkedc#214]
My issue involves uses of `void*` for purposes of encoding polymorphism. I know this is an active area of development, so this issue is equally to ask about a workaround, not just a fix. 

The problem is encoded in the example below. A legacy library is using a function pointer that takes a `void*` argument, and yet I want to pass a checked function to it, which uses that argument at a particular type. The two ways I can think of to check this code (the two implementations of `foo` below) are not accepted:
```
struct s { int x; int y; };

int app(void (*p_func)(void*), void* p_arg);

void foo(void* p_arg : itype(_Ptr<struct s>)) { // FAILS: mismatch of interface type
  _Ptr<struct s> ps = p_arg;
  ps->x = 5;
}

/* alternatively:
void foo(void* p_arg) {
  _Ptr<struct s> ps = (_Ptr<struct s>)p_arg; // FAILS: says p_arg has no bounds
  ps->x = 5;
}
*/

void bar(_Ptr<struct s> ps)
{
  app(foo,(void *)ps);
  ps->x = 5;
}
```
Advice appreciated!

**Comment by dtarditi** [comment]
You can use the `_Assume_bounds_cast` operator instead of the cast operator for the second alternative.:
```
void foo(void* p_arg) {
 // assume that it is correct to cast from void * to Ptr<T>
_Ptr<struct s> ps = _Assume_bounds_cast<_Ptr<struct s>>(p_arg); 
ps->x = 5;
}
```

 We're following the same route as C++ of trying to make the existing cast operator safer.  We've taken a slightly different tack.  Because we've introduced new pointer types, we get to define what the meaning of the cast operator is for those types.   

We require that things be statically provable for the cast operator when the target is a checked pointer..  For casts to Ptr types, we require that it be statically provable that the source pointer actually point to memory large enough to hold an instance of the Ptr type.   For casts to _Array_ptr, we flow the bounds information through the cast operator.  We check validity of bounds (if necessary) at the use of the cast expression (for example, as the RHS of assignment to a variable with a bounds declaration).

We introduce new operators _Dynamic_bounds_cast and _Assume_bounds_cast for cases where bounds need to be checked dynamically or assumed to be true.

The long-term plan for void * usage for parameter types in existing libraries is to allow a bounds-safe interface type to be specified that is a polymorphic function type.    This hasn't been implemented yet.   We allow a polymorphic function to be specified using _Forany(T), which binds a type variable:

The polymorphic version of foo can be: declared as:
```
_For_any(T) void foo(ptr<T> p_parg);;
````
To allow a version of `foo` with an interface type, we might have syntax like:
```
itype(_For_any(T)) void foo(void *parg : itype(ptr<T>)) 
```

**Comment by mwhicks1** [comment]
That did it. Thanks!
