### ISSUE TITLE
Create examples of using null-terminated arrays

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc#217]

**Comment by mwhicks1** [comment]
I made a bunch of comments/questions on the pull request. Can you check those out David?

**Comment by mwhicks1** [comment]
One other one: Can we give a sensible type to strlen? That is, you want to relate the returned length with the count of the string parameter. 

One approach would be to return a pair of the string and its new length. But this extra allocation would be wasteful. Another approach would be to make strlen a macro, so that the length is basically inlined in the given. This would allow the compiler to make the discovered bound usable by the code that follows.

**Comment by dtarditi** [comment]
The strlen issue is already covered in the design by using where clauses on return bounds.    Implementing where clauses is on our implementation plan.
