### ISSUE TITLE
Bogus casts from _Ptr<void> seem to be allowed

### ISSUE THREAD

**Issue by mwhicks1** [Microsoft/checkedc#232]
I think that, in general, casting from `_Ptr<void>` to another sort of pointer type should not be allowed in checked code. But it seems to be allowed, even when the result is a memory safety violation. The following example converts a pointer to an int to a pointer to a multi-word struct.
```
#pragma BOUNDS_CHECKED ON

struct foo {
  int x;
  int y;
};

_Ptr<struct foo> launder(_Ptr<void> x) {
  return (_Ptr<struct foo>)x;
}

int main(int argc, _Nt_array_ptr<char> argv[] : count(argc)) {
  int x = 0;
  _Ptr<int> p = &x;
  _Ptr<struct foo> ps = launder(p);
  ps->y = 5; /* out of bounds -- overwrites p */
  return 0;
}
```

**Comment by dtarditi** [comment]
This is passing the compiler because checking of bounds declaration isn't turned on yet.  The checking is still a work-in-progress and would give too many errors.  When it is turned, this will fail the checking.   Ptr<void> has a bounds of 1 character, so any cast to anything larger than 1 character will fail.

The long-term plan is to disable any conversions from checked pointers to void once support for generics is implemented.

**Comment by dtarditi** [comment]
Checked C doesn't allow implicit casts from Ptr<void> to other types.  If  the code is written as:
```
struct foo {
  int x;
  int y;
};

_Ptr<struct foo> launder(_Ptr<void> x) {
  return x;
}
```
It is rejected:
```
tmp.c:9:10: error: returning '_Ptr<void>' from a function with incompatible result type '_Ptr<struct foo>'
  return x;
         ^
1 error generated.
```

The issue is that the code contains an explicit cast operation.   Checked C does allow explicit cast operations in checked blocks, with the provision that there be static checking that ensures bounds safety is preserved.  We thought about introducing a new `static_bounds_cast` operator, but it seemed easier to stick with allowing C-style casts and require more static checking: 
-  For C-style casts to Ptr type, it has to be provable at compile-time that the source pointer points to an area of memory with enough space for a 1 element of target pointer's referent type.
- For `_Array_ptr`, the bounds of the source value pass through.  There are adjustments for relative alignment when the sizes of source/target reference types differ.

As I mentioned earlier, the static checking in the compiler was not implemented.   I've created a pull request for the compiler (https://github.com/Microsoft/checkedc-clang/pull/414) that adds the checking for casts to and from _Ptr type.  With this pull request, the compiler now gives an error message:
```
tmp.c:9:10: error: cast source bounds are too narrow for '_Ptr<struct foo>'
  return (_Ptr<struct foo>) x;
         ^~~~~~~~~~~~~~~~~~~~
tmp.c:9:10: note: (expanded) required bounds are 'bounds((_Ptr<struct foo>)x, (_Ptr<struct foo>)x + 1)'
tmp.c:9:10: note: (expanded) inferred bounds are 'bounds((_Array_ptr<char>)x, (_Array_ptr<char>)x + 1)'

```
The spec says that preserving type-safety for casts between pointers to struct types is future work (beyond the scope of just enforcing bounds safety). The issue is overlapped members having different types. from pointers to struct types is future work.  The spec currently allows the following:
```
struct overlap {
   Ptr<int> badptr;
   int y;
}

_Ptr<struct foo> s  = ...
Ptr<overlap> P = (Ptr<overlap>) 
```
