### ISSUE TITLE
Can you instead upload your spec in the Markdown language that's more amenable to GitHub?

### ISSUE THREAD

**Issue by KumarL** [Microsoft/checkedc#26]

**Comment by qin-nz** [comment]
Maybe release a pdf version is a better choice.

**Comment by awruef** [comment]
There's a PDF here: https://github.com/Microsoft/checkedc/releases/download/v0.5-final/checkedc-v0.5.pdf

**Comment by qin-nz** [comment]
@KumarL  The result of spec is a document with more than 100 bibliographies.
Markdown cannot reference them automatically.

**Comment by HyperHCl** [comment]
MSR Redmond has a more scholar Markdown dialect called Madoko, which can be more suitable for this purpose. But don't even think about GitHub presentation…

**Comment by dtarditi** [comment]
The consensus seems to be the GitHub Markdown isn't suitable for this document.

**Comment by KumarL** [comment]
Sure, but do you mind sharing what reasons those consensus was built on? Also, whose consensus -- your users, or your developers?

**Comment by HyperHCl** [comment]
> @dtarditi I did try using Pandoc to convert the LaTex to Github markdown and HTML. 

Footnote is not a GitHub markdown thing, so ... perhaps you should try the pandoc enhanced markdown instead. The "more amenable to GitHub" goal is largely unrealistic (markdown still looks more familiar though).

* * *

On the other hand, I tried using Madoko.NET to convert the file into a largely Pandoc-like Markdown dialect:

https://github.com/HyperHCl/checkedc/tree/master/madoko
[html.zip](https://github.com/Microsoft/checkedc/files/491775/html.zip)

**Comment by dtarditi** [comment]
I actually tried the Pandoc enhanced markdown a while ago because of footnotes and the generated markdown still had issues.

@HyperHCI, thanks for trying out using Madoko!   I look at the generated mdk files that you posted and they look pretty good.   The text seems to be fairly intact.  What are your thoughts on how we might use Madoko for the Checked C project?   One possibility is that we consider switching to using Madoko for editing/creation of the specification document.  From Madoko, we could then generate HTML or PDF.   Madoko is open-source too, but it isn't as well-known as LaTex and doesn't have the same community.  

Another possibility is to just aim for producing an HTML version of the specification from the LateX sources.  There are tools that could use for this: [https://en.wikipedia.org/wiki/LaTeXML](https://en.wikipedia.org/wiki/LaTeXML).

**Comment by HyperHCl** [comment]
> What are your thoughts on how we might use Madoko for the Checked C project? One possibility is that we consider switching to using Madoko for editing/creation of the specification document.

That means following the suit of [F star](https://fstar-lang.org/tutorial/), [Koka](http://research.microsoft.com/en-us/um/people/daan/koka/doc/kokaspec.html) (the language Madoko is written in), and [Madoko](http://research.microsoft.com/en-us/um/people/daan/madoko/doc/reference.html) itself. Madoko seems well-tested by its creators and their friends in spec-writing.

> Madoko is open-source too, but it isn't as well-known as LaTex and doesn't have the same community.

Yeah. As shown with the links above, well-known usages of Madoko are mostly MSR dogfooding.
