### ISSUE TITLE
Bounds-safe interface for free incompatible with nt_array_ptr

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [Microsoft/checkedc#290]
The bounds-safe interface for the stdlib function `free` in `stdlib_checked.h` assumes that the argument has bounds that include at least one byte of memory:
`void free(void *pointer : byte_count(1));`

However, we define `nt_array_ptr` to have bounds of `count(0)` by default (and then do bounds widening), which means that `nt_array_ptr` type memory cannot be sent to `free`.

Since developers free strings very regularly, forcing them to add something extra to that call in the case of `nt_array_ptr` seems both confusing and bothersome. Can we do something under the hood to support calls to `free` with `nt_array_ptr` args, without losing the bounds checking we have for `array_ptr`?

**Comment by awruef** [comment]
It seems like `free` could be `byte_count(0)`? Any reason why not? Sounds to me like "`free` takes a pointer to some object where we don't really know anything about the size (and if we did it wouldn't matter because we don't communicate the size to `free` anyway)"?

**Comment by dtarditi** [comment]
We can either change the bounds-safe interface to count(0) or add an alternate inline function definition of free for _nt_array_ptr.  I'm leaning toward adding an alternate definition for nt_array_ptr.     A nice thing about bounds-safe interfaces is that they are opt-in, so it is OK to suggest that calls be changed.  Note that we have a problem with needing an alternate bound-safe interface for strncmp too (issue #291). 

We could place the alternate definition in an opt-in header file or include it in the existing header file.

**Comment by AnnaKornfeldSimpson** [comment]
In yesterday's meeting, we discussed changing the bounds-safe interface for `free`. I think @Prabhuk was checking to make sure it was ok to free 0 bytes?

**Comment by dtarditi** [comment]
Currently we have a bounds-safe interface for `free` of byte_count(1).   @Prabhuk checked the C11 Specification.  It is possible to allocate zero-sized objects, which means you it is possible to free them.  From section 7.22.3 of the C11 Specification about `malloc` and other allocation functions:

> If the size of the space requested is zero, the behavior is implementation-deﬁned: either a null pointer is returned, or the behavior is as if the size were some nonzero value, except that the returned pointer shall not be used to access an object.

I think we should change the bounds-safe interface for `free` to be `byte_count(0)`.

We did consider having a bounds-safe interface for `free` that didn't have have any bounds:
```
void free(void * : itype(_Array_ptr<void>));
```

The problem is that an `array_ptr` with unknown bounds can be created with any value:
```
_Array_ptr<int> p = (_Array_ptr<int>) 0xaaa;
```
is valid.

By requiring that a checked pointer passed to `free` have some bounds, we have the weak guarantee that the pointer is at least derived from a pointer to a valid object.  That's better than having a pointer that was never derived from a pointer to a valid object.

**Comment by AnnaKornfeldSimpson** [comment]
I agree with `byte_count(0)` - and the logic above. I'll submit a PR for this.
