### ISSUE TITLE
Checked C compiler on Visual Studio 2017

### ISSUE THREAD

**Issue by AkumaNemui** [microsoft/checkedc#352]
Hello,

I am currently working on an evaluation of several languages in which Checked C is one of them.
And I have a problem with the compiler.
Although I install the 64bits version of Checked C Clang, Microsoft Visual Studio 2017 only finds it in 32bits version.
Is this a compatibility issue between Visual Studio 2017 and the compiler? Or a problem setting Visual Studio?

**Comment by dtarditi** [comment]
Are you running the compiler from the Visual Studio command line or the Visual Studio IDE?

If you are running it from the command line, you may need to use the Visual Studio x64 Native Tools Command Prompt, instead of the Visual Studio Developer Command prompt.   Otherwise you'll get link errors when compiling test programs.

**Comment by AkumaNemui** [comment]
I run the compiler from the Visual Studio IDE.

**Comment by dtarditi** [comment]
This bug report is old at this point.  It isn't clear the problem still exists.
