### ISSUE TITLE
how  to do runtime check

### ISSUE THREAD

**Issue by zhangyibobobo** [Microsoft/checkedc#50]
Dear Mr/Miss:
 I did a test, that use the codes as follows:
void add()
{
    int a checked[2]:bounds(a, a + 2);
    int b checked[2]:bounds(b, b + 2);  
    for (int i = 0; i < 5; i++)
    {
        a[i] += b[i];
    }
    return;
}
After I compiled these codes and generated an .o file, I compared the call stack, it is as the same as these codes:
void add()
{
    int a checked[2]:bounds(a, a + 2);sss
    int b checked[2]:bounds(b, b + 2);

```
for (int i = 0; i < 5; i++)
{
    a[i] += b[i];
}

return;
```

}

Did not add any codes after compiled.
So I have two question：
1. How checked-c does runtime check?
2. How can I do this test? I want test runtime check, can you give me some examples?

Wait for your replay
Thank you 
Best wishs

**Comment by dtarditi** [comment]
Thanks for your interest in Checked C!   The implementation in clang is still at an early stage. We have not implemented the runtime bounds checks in clang yet.  

We have implemented parsing and type checking of the new array types and pointer types.  We also have implemented parsing of the new bounds declarations.   We are finishing up implementing type checking of the new bounds declarations..  That is why the example compiles but does not have any runtime checks.  

The status of the Checked C implementation is described [here](https://github.com/Microsoft/checkedc-clang/README.md).

**Comment by zhangyibobobo** [comment]
Thanks for your replay!  And I want to know when can support runtime bounds checks? What's the plan?
 I have another question, what's the difference between Checked C and static scan tools, such as coverity or fortify, which also can find some out of bounds issues.

Thank you 
 Best wishs

**Comment by dtarditi** [comment]
We are aiming to add runtime bounds checks by the December/January time frame.  We will also aiming to check bounds declarations for pointers to constant-sized data by then.

It is pretty straightforward to add the runtime bounds checks.    However, it is also important to check that the bounds declarations written by programmers are correct.   If the bounds declarations are incorrect, it may not mean much to check the bounds.   Most of the work will be checking the bounds declarations.   We are focusing on constant-sized data first because it is easier to check bounds declarations for that.

Bounds declaration should follow logically from other information in the program.  As an example, if a programmer declares an array  with 5 elements (`int a[5]`), any bounds declaration for pointers derived from 'a' must respect the bounds of `a`.   A programmer should not be able to declare bounds of the form `bounds(a, a + 6)`. 

There are several differences between Checked C and static analysis tools:

- For programs that use only checked pointer types, Checked C aims to catch all out-of-bounds errors.  Static analysis tools make unsound assumptions about programs and cannot guarantee that they catch all out-of-bounds errors. 
- In Checked C, you have to update your source code to describe the bounds.  Static analysis tools do not usually require you to modify your code.    There is a trade-off between the two approaches: you provide more information about your program with Checked C, but you get stronger checking.
- Checked C combines static checking and dynamic checks, while static analysis requires that everything be checked statically.   This leads to problems with false positives for static checking tools.  A false positive is a report of an error that is not really an error because it can never happen.  With Checked C, bounds checks are deferred until runtime.  This avoids false positives.  If the error cannot happen, it will never happen at runtime.  If the programmer is wrong, though, the program may fail a bounds check at runtime.

A goal for Checked C is to provide bounds checking that is comparable to what you can get with C# or Java.  In C# or Java, bounds checking is done automatically.   However, a program can still fail with a bounds error at runtime.  It can be quite difficult to prove that C# and Java programs do not fail due to bounds errors at runtime.
